
obj-$(CONFIG_BCACHE_FS)	+= bcachefs.o

bcachefs-y		:= acl.o alloc.o bkey.o bkey_methods.o bset.o\
	btree_cache.o btree_gc.o btree_io.o btree_iter.o btree_update.o\
	buckets.o chardev.o checksum.o clock.o compress.o debug.o dirent.o\
	error.o extents.o fs.o fsck.o fs-io.o inode.o io.o journal.o keylist.o\
	migrate.o move.o movinggc.o opts.o siphash.o six.o super.o super-io.o\
	sysfs.o tier.o trace.o util.o xattr.o
