obj-$(CONFIG_ZSTD)	+= zstd.o
zstd-y			:=	\
	entropy_common.o	\
	error_private.o		\
	fse_compress.o		\
	fse_decompress.o	\
	huf_compress.o		\
	huf_decompress.o	\
	xxhash.o		\
	zstd_common.o		\
	zstd_compress.o		\
	zstd_decompress.o
